MAIN_MENU=MENU PRINCIPAL
USER_MODE=Mode Utilisateur
ADMIN_MODE=Mode Administrateur
QUIT=Quitter

USER_MENU=MODE UTILISATEUR
TEXT_CMD=Commande textuelle
SIMULATION=Simulation
IMAGE=Traitement d'image
BACK=Retour

ADMIN_MENU=MODE ADMINISTRATEUR
VIEW_LOGS=Voir les logs

CHOICE=Votre choix :
INVALID=Entrée invalide
EXIT=Fin du programme

ADMIN_LOGIN=Identifiant administrateur :
ADMIN_PASS=Mot de passe :
ADMIN_OK=Authentification réussie
ADMIN_KO=Identifiant ou mot de passe incorrect

