MAIN_MENU=MAIN MENU
USER_MODE=User Mode
ADMIN_MODE=Administrator Mode
QUIT=Quit

USER_MENU=USER MODE
TEXT_CMD=Text command
SIMULATION=Simulation
IMAGE=Image processing
BACK=Back

ADMIN_MENU=ADMIN MODE
VIEW_LOGS=View logs

CHOICE=Your choice :
INVALID=Invalid input
EXIT=Program terminated

ADMIN_LOGIN=Administrator login:
ADMIN_PASS=Password:
ADMIN_OK=Authentication successful
ADMIN_KO=Wrong login or password
