/* ============================================================
   Fichier  : lang_en.conf
   Projet   : PFR1 – Projet Fil Rouge
   Auteur   : CHENTIR Hakim
   ------------------------------------------------------------
                        DESCRIPTION
   ------------------------------------------------------------
   Ce fichier contient les traductions en anglais de
   l'interface utilisateur. Chaque ligne définit une clé
   et sa valeur correspondante.
   ------------------------------------------------------------
                        RÔLE DU MODULE
   ------------------------------------------------------------
   fournir les textes en anglais pour l'interface
   permettre l'affichage des menus et messages
   faciliter la maintenance des traductions
   ============================================================ */

MAIN_MENU=MAIN MENU
USER_MODE=User Mode
ADMIN_MODE=Administrator Mode
QUIT=Quit

USER_MENU=USER MODE
VOICE_CMD=Voice command
TEXT_CMD=Text command
SIMULATION=Simulation
IMAGE=Image processing

IMAGE=Image processing
LOAD_IMAGE=Load image
FIND_OBJECTS=Find objects (draw bounding boxes)
CONVERT_NB=Convert to monochrome
FLIP_VERTICAL=Flip vertically
QUANT=Quantization
SAVE_IMAGE=Save and open image
CONVERTED=Conversion completed successfully
IMAGE_MENU=IMAGE MENU
IMAGE_SAVE_SUCCESS=Image saved successfully
IMAGE_SAVE_FAIL=Failed to save image
ROTATE=Rotate image 90° (clockwise)

CMD_PROMPT=Ready to read your commands, type exit to quit...
VOC_ACTIVE=Voice mode is active...
VOC_ERR=There was an error launching the voice module, quitting...

TRANSCRIPT=Transcript recieved:


BACK=Back

ADMIN_MENU=ADMIN MODE
VIEW_LOGS=View logs
ACCESS_DENIED=Administrator access denied

TEXT_CMD_CHOSEN=Text command mode selected
SIMULATION_CHOSEN=Simulation mode selected
IMAGE_CHOSEN=Image processing mode selected
BACK_CHOSEN=Returning to main menu
LOG_CHOSEN=Viewing logs selected

CHOICE=Your choice >
INVALID=Invalid input
EXIT=Program terminated

