# Fichier de configuration pour le module simulation (PFR1)

[WINDOW]
#Dimensions de la fenêtre
title = Simuation Robot
background_color = white

[SCALE]
#Echelle 1 mètre = N pixels
m_to_p = 100 #metres to pixels

[ENVIRONNEMENT]
#Bordures de l'environnement
x_min = -5 #Dimensions en mètres (-500 pixels)
x_max = 5
y_min = -5
y_max = -5

[ROBOT]
#Apparence du robot
shape = triangle
color = black
size = 0.5
traj_color = red
pen_size = 2 #Pas des mètres ni des pixels

[OBSTACLES]
obs_color = blue

[DEFAULT_VALUES]
#Valeurs par défaut (si non spécifiées lors des commandes)
df_dist = 1.0
df_angle = 90.0

[SIMULATION]
#Vitesse d'animation
speed = normal

